<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ameri-LT606" name="Test" tests="3" failures="3" timestamp="19 Nov 2019 13:02:55 GMT" time="26.409" errors="0">
  <testcase name="Tc_Login_001" time="0.015" classname="ssms.SSMS_Automation.TestCase.LoginRegistration">
    <failure type="java.lang.AssertionError" message="Fail due to exception null">
      <![CDATA[java.lang.AssertionError: Fail due to exception null
	at ssms.SSMS_Automation.modules.Login.logIn(Login.java:28)
	at ssms.SSMS_Automation.TestCase.LoginRegistration.Tc_Login_001(LoginRegistration.java:15)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Tc_Login_001 -->
  <testcase name="Tc_Login_002" time="0.001" classname="ssms.SSMS_Automation.TestCase.LoginRegistration">
    <failure type="java.lang.AssertionError" message="Fail due to exception null">
      <![CDATA[java.lang.AssertionError: Fail due to exception null
	at ssms.SSMS_Automation.modules.Login.logIn(Login.java:28)
	at ssms.SSMS_Automation.TestCase.LoginRegistration.Tc_Login_002(LoginRegistration.java:21)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Tc_Login_002 -->
  <testcase name="Tc_Login_003" time="0.001" classname="ssms.SSMS_Automation.TestCase.LoginRegistration">
    <failure type="java.lang.AssertionError" message="Fail due to exception null">
      <![CDATA[java.lang.AssertionError: Fail due to exception null
	at ssms.SSMS_Automation.modules.Login.logIn(Login.java:28)
	at ssms.SSMS_Automation.TestCase.LoginRegistration.Tc_Login_003(LoginRegistration.java:27)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Tc_Login_003 -->
</testsuite> <!-- Test -->
